apiVersion: v1

kind: Service

metadata:

  name: karan-devops-dashboard-service

  namespace: karan-dashboard

spec:

  type: NodePort

  selector:

    app: karan-devops-dashboard

  ports:

    - name: http

      port: 5000

      targetPort: 5000

      nodePort: 30080
