apiVersion: v1

kind: Service

metadata:

  name: karan-mysql-service

  namespace: karan-dashboard

spec:

  type: ClusterIP

  selector:

    app: karan-mysql

  ports:

    - name: mysql

      port: 3306

      targetPort: 3306
